export { default as Moto } from './moto.js'
export { default as TyresNew } from './tyresNew.js'
export { default as TyresUsed } from './tyresUsed.js'
export { default as Trips } from './trips.js' 
export { default as Users } from './users.js'
export { default as PartsNew } from './partsNew.js'
export { default as PartsUsed } from './partsUsed.js'